# Generated by Django 3.2.7 on 2021-10-06 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materiaPrima',
            fields=[
                ('materiaPrimaId', models.AutoField(primary_key=True, serialize=False)),
                ('materiaPrima_codigo', models.IntegerField(default=0)),
                ('materiaPrima_categoria_id', models.CharField(default=0, max_length=15)),
                ('materiaPrima_descripcion', models.CharField(default='---', help_text='Por favor ingrese una descripción', max_length=10)),
                ('materiaPrima_existencias', models.IntegerField(default=0)),
                ('materiaPrima_unidad', models.CharField(default=0, help_text='ingrese las unidades de materia prima', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('proveedorId', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor_Name', models.CharField(default='0', max_length=60)),
                ('proveedor_Telefono', models.IntegerField(blank=True, null=True)),
                ('proveedor_Direccion', models.CharField(default='0', max_length=50)),
                ('proveedor_Email', models.CharField(default='0', max_length=50)),
                ('proveedor_Nit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('entradaMateriaPrimaId', models.AutoField(primary_key=True, serialize=False)),
                ('movimientoFecha', models.DateField(default=0, help_text='Por favor indique la fecha del movimiento')),
                ('movimientoLote', models.CharField(default='---', help_text='Por favor ingrese el lote', max_length=10)),
                ('movimientoCantidad', models.IntegerField(default=0, help_text='Por favor ingrese la cantidad total de unidades de materia prima a registrar')),
                ('movimientoPrecioUnitario', models.FloatField(default=0, help_text='Por favor ingrese el precio unitario de la materia prima')),
                ('movimientoTipo', models.IntegerField(default='---')),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevosRegistros.materiaprima')),
                ('movimientoProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevosRegistros.proveedores')),
            ],
        ),
    ]
