# Generated by Django 3.2.7 on 2021-10-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevosRegistros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movimientos',
        ),
    ]
