# Generated by Django 3.2.7 on 2021-10-06 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuevosRegistros', '0002_delete_movimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('entradaMateriaPrimaId', models.AutoField(primary_key=True, serialize=False)),
                ('movimientoFecha', models.DateField(default=0, help_text='Por favor indique la fecha del movimiento')),
                ('movimientoLote', models.CharField(default='---', help_text='Por favor ingrese el lote', max_length=10)),
                ('movimientoCantidad', models.IntegerField(default=0, help_text='Por favor ingrese la cantidad total de unidades de materia prima a registrar')),
                ('movimientoPrecioUnitario', models.FloatField(default=0, help_text='Por favor ingrese el precio unitario de la materia prima')),
                ('movimientoTipo', models.IntegerField(default='---')),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevosRegistros.materiaprima')),
                ('movimientoProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevosRegistros.proveedores')),
            ],
        ),
    ]
