# Generated by Django 3.2.7 on 2021-10-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevosRegistros', '0004_auto_20211012_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='Id',
            new_name='Id_id',
        ),
    ]
