# Generated by Django 3.2.7 on 2021-10-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevosRegistros', '0005_rename_id_movimientos_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientos',
            old_name='Id_id',
            new_name='idMateriaPrima',
        ),
    ]
