# Generated by Django 3.2.7 on 2021-10-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuevosRegistros', '0006_rename_id_id_movimientos_idmateriaprima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='idMateriaPrima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refMateriaprimaX', to='nuevosRegistros.materiaprima'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='movimientoProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refProveedorX', to='nuevosRegistros.proveedores'),
        ),
    ]
