# Generated by Django 3.2.7 on 2021-10-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuevosRegistros', '0007_auto_20211012_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='idMateriaPrima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refMateriaprima', to='nuevosRegistros.materiaprima'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='movimientoProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refProveedor', to='nuevosRegistros.proveedores'),
        ),
    ]
