# Generated by Django 3.2.7 on 2021-10-12 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevosRegistros', '0008_auto_20211012_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='movimientoFecha',
            field=models.DateField(default=datetime.date.today, help_text='Por favor indique la fecha del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='movimientoLote',
            field=models.CharField(default='', help_text='Por favor ingrese el lote', max_length=10),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='movimientoTipo',
            field=models.IntegerField(default=0),
        ),
    ]
